export const PLAYER_UI_COPY = {
  hostLockedPlaySeek: 'Phát / tua · theo Host',
  hostLockedPlay: 'Phát · theo Host',
  hostLockedSpeed: 'Tốc độ · theo Host',
  hostLockedEpisode: 'Đổi tập · theo Host',
  hostLockedVideo: 'Điều khiển video · theo Host',
  hostLockedPrev: 'Tập trước · theo Host',
  hostLockedNext: 'Tập sau · theo Host',
  hostHintSuffix: ' · theo Host',
  play: 'Phát',
  pause: 'Tạm dừng',
  playShortcut: 'Phát (K)',
  pauseShortcut: 'Tạm dừng (K)',
  mute: 'Tắt tiếng',
  unmute: 'Bật tiếng',
  muteShortcut: 'Tắt tiếng (M)',
  unmuteShortcut: 'Bật tiếng (M)',
  fullscreen: 'Toàn màn hình',
  exitFullscreen: 'Thoát toàn màn hình',
  fullscreenShortcut: 'Toàn màn hình (F)',
  exitFullscreenShortcut: 'Thoát toàn màn hình (F)',
  settingsPlayback: 'Cài đặt phát',
  settingsWatch: 'Cài đặt xem',
  speedLabel: 'Tốc độ',
  qualityLabel: 'Chất lượng',
  qualityAuto: 'Auto',
  pipEnter: 'Picture-in-Picture',
  pipExit: 'Thoát PiP',
  errorNetwork: 'Gặp lỗi mạng nghiêm trọng, hãy thử khôi phục',
  errorMedia: 'Gặp lỗi phương tiện nghiêm trọng, hãy thử khôi phục',
  errorGeneric: 'Đã có lỗi xảy ra với video!',
  errorUnsupported: 'Thiết bị không hỗ trợ phát video này',
  errorPip: 'Không thể bật Picture-in-Picture',
  errorRetryTitle: 'Rất tiếc vì sự cố này!',
  errorRetryAction: 'Làm mới và tiếp tục xem',
  findEpisodePlaceholder: 'Tìm tập',
  episodeListTitle: 'Danh sách tập',
  creatingRoom: 'Đang tạo...',
  createWatchParty: 'Tạo Phòng Xem Chung',
  filmContentHeading: 'Nội dung phim',
  theatricalNote: 'Phim chiếu rạp',
  settingsWatchOptions: 'Tuỳ chọn xem',
  lightLabel: 'Light',
  lightHint: 'Chỉ thiết bị của bạn',
  autoPlayLabel: 'Auto Play',
  autoNextLabel: 'Auto Next',
  theaterLabel: 'Theater',
  deviceOnlyHint: 'Chỉ thiết bị của bạn',
  hostSyncHint: 'Theo Host',
  roomSyncHint: 'Đồng bộ phòng',
  moreActions: 'Thêm thao tác',
  more: 'Thêm',
  reportError: 'Báo lỗi',
  reportEpisode: 'Báo lỗi tập',
  share: 'Chia sẻ',
  shareEpisodeLink: 'Chia sẻ link tập',
  prevEpisode: 'Tập trước',
  nextEpisode: 'Tập sau',
  prevShort: 'Trước',
  nextShort: 'Sau',
  reportSuccess: 'Đã ghi nhận báo cáo lỗi. Cảm ơn bạn!',
  shareSuccess: 'Đã sao chép link tập đang xem!',
  shareFailed: 'Không thể sao chép link. Hãy thử lại.',
} as const;

export type PlayerUiCopyKey = keyof typeof PLAYER_UI_COPY;
